### npm run start | npm run build | npm run dev
GET  http://localhost:3333/

### /users
GET http://localhost:3333/users

### /users/new 
POST http://localhost:3333/users/new
Content-Type: application/json

{
    "name": "Duds, the second ",
    "email": "stud@paartner",
    "password": "L1",
    "type": "A"
}

### DELETE /users/:id/delete
DELETE http://localhost:3333/users/1/delete

