### npm run start | npm run build | npm run dev
GET  http://localhost:3333/

### /users
GET http://localhost:3333/users

### /users/new 
POST http://localhost:3333/users/new
Content-Type: application/json

{
    "name": "Stud, o duds",
    "email": "stud@paartner",
    "password": "L1",
    "type": "A"
}

### DELETE /users/:id/delete
DELETE http://localhost:3333/users/b5df6104-5fde-4169-b5f5-fa5f3b3b1cc8/delete

